version: "3.8"

services:

  web1:
    image: my-nginx-container
    container_name: vertex-web1
    ports:
      - "8081:80"

  web2:
    image: my-nginx-container
    container_name: vertex-web2
    ports:
      - "8082:80"

  web3:
    image: my-nginx-container
    container_name: vertex-web3
    ports:
      - "8083:80"

  web4:
    image: my-nginx-container
    container_name: vertex-web4
    ports:
      - "8084:80"

  web5:
    image: my-nginx-container
    container_name: vertex-web5
    ports:
      - "8085:80"