version: "3.8"

services:

  hq: 
    image: my-nginx-container
    container_name: hq
    ports:
      - "8081:80"

  cloud:
    image: my-nginx-container
    container_name: cloud
    ports:
      - "8082:80"

  security:
    image: my-nginx-container
    container_name: security
    ports:
      - "8083:80"

  customer:
    image: my-nginx-container
    container_name: customer
    ports:
      - "8084:80"

  research:
    image: my-nginx-container
    container_name: research
    ports:
      - "8085:80"
